### ISSUE TITLE
XGBoost models

### ISSUE THREAD

**Issue by nikolaydubina** [gorse-io/gorse#203]
Since you guys deal with tabular data XGBoost would be a nice fit. 

Also, you can avoid IPC by implementing it in native Go say with [go-featureprocessing](http://github.com/nikolaydubina/go-featureprocessing) + [leaves](https://github.com/dmitryikh/leaves).

Cheers,

-- Nikolay

**Comment by zhenghaoz** [comment]
I prefer deep learning based model in the future. It is the trending.😂

**Comment by nikolaydubina** [comment]
I mean, if you guys can manage to run DL on GPUs in native Go, that would be great. Or if you guys make DL work for tabular datasets.

Both of the above are unbelievably hard and no-one could do so far in last 10+ years.

Probably, you would go for some compromise, but I hope you benchmark your solution not against other Go but against state-of-the-art which is Python GPU CUDA non-tabular datasets.

**Comment by zhenghaoz** [comment]
The only way to deep learning is using C++ since most deep learning frameworks  are implemented by C++. We plan to use CGO to utilize some existed deep learning infrastructures.

**Comment by nikolaydubina** [comment]
> cgo to use C++

Other way is to make (g)RPC calls from native Go to C++ to get best of both worlds. Penalty of CGO is large, last time I checked: https://github.com/nikolaydubina/go-ml-benchmarks

Besides, [cgo != Go](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=757s)

Good luck guys!

**Comment by zhenghaoz** [comment]
Thank you Nikolay
