### ISSUE TITLE
Information regarding valid time formats.

### ISSUE THREAD

**Issue by avinashkurup** [gorse-io/gorse#232]
Hi,
    I recieve errors in the form of 'failed to parse datetime `` at line x' in the console while loading csv's. Could you point me to the valid datetime formats acceptable for timestamps in the csv file? Any help would be appreciated.

Thanks,
Avinash.

**Comment by zhenghaoz** [comment]
Do you have timestamps? It seems the field of timestamp is empty.

**Comment by avinashkurup** [comment]
> Do you have timestamps? It seems the field of timestamp is empty.

Timestamps fields are being passed in the Advanced > feedback console, I get errors as

failed to parse datetime `81` at line 6failed to parse datetime `29-01-2021 07:01` at line 10failed to parse datetime `30-01-2021 08:01` at line 22failed to parse datetime `29-01-2021 01:01` at line 26failed to parse datetime `12-03-2021 05:03` at line 29failed to parse datetime `29-01-2021 11:01` at line 31failed to parse datetime `29-01-2021 12:01` at line 37failed to parse datetime `01:21.7` at line 41failed to parse datetime `30-01-2021 07:01` at line 56failed to parse datetime `30-01-2021 07:01` at line 59failed to parse datetime `30-01-2021 07:01` at line 60failed to parse datetime `152` at line 68failed to parse datetime `05-10-2020 03:31` at line 79failed to parse datetime `29-01-2021 06:01` at line 86failed to parse datetime `29-01-2021 06:01` at line 92failed to parse datetime `29-01-2021 07:01` at line 97failed to parse datetime `29-01-2021 07:01` at line 98failed to parse datetime `20-10-2020 12:33` at line 118failed to parse datetime `20-04-2021 04:04` at line 

and so on in the error panel.

Thanks ,
Avinash.

**Comment by zhenghaoz** [comment]
Gorse use [araddon/dateparse](https://github.com/araddon/dateparse) to parse timestamps. However, it seems that your timestamps are not supported by [araddon/dateparse](https://github.com/araddon/dateparse). Maybe, you could follow date formats listed by [araddon/dateparse](https://github.com/araddon/dateparse).

**Comment by avinashkurup** [comment]
Hi,
> Gorse use [araddon/dateparse](https://github.com/araddon/dateparse) to parse timestamps. However, it seems that your timestamps are not supported by [araddon/dateparse](https://github.com/araddon/dateparse). Maybe, you could follow date formats listed by [araddon/dateparse](https://github.com/araddon/dateparse).

The format that we use for timestamps in the csv is as "2013-04-01 22:43:22" but we still get parsing errors as above.

**Comment by zhenghaoz** [comment]
Could you provide a minimal sample of CSV file to reproduce this failure? That's really weird.
