### ISSUE TITLE
NOAUTH on loading data into feedback through console.

### ISSUE THREAD

**Issue by avinashkurup** [gorse-io/gorse#235]
Hi,
Faced this error, NOAUTH, Authentication required. Got this error while trying to inport feedback into Gorse. I'm using v0.2.4 with Postgresql as backend.
![NOAUTH](https://user-images.githubusercontent.com/681657/129580195-3de7fd83-5a26-4897-a571-bcc0ac1c1373.PNG)
 Please tell me how to fix this.

Thank you,
Avinash.

**Comment by zhenghaoz** [comment]
Hi. Have you include username and password in the DSN or postgres in the configuration file?

**Comment by avinashkurup** [comment]
> Hi. Have you include username and password in the DSN or postgres in the configuration file?

Yes I have included username and password in the config file under data_store.
