### ISSUE TITLE
storage: optimize MySQL schema with index

### ISSUE THREAD

**Issue by zhenghaoz** [gorse-io/gorse#264]
Currently, there is only one index on `feedback(user_id)`. More indices are required to optimize the performance of differrent workload on MySQL.

https://github.com/zhenghaoz/gorse/blob/125c8f4a1a8c52f505a9e663c8864d329270f504/storage/data/sql.go#L62-L106

**Comment by lucmichalski** [comment]
Why don't you use gorm ? https://gorm.io/index.html

**Comment by zhenghaoz** [comment]
> Why don't you use gorm ? https://gorm.io/index.html

The data models in Gorse is simple, ORM will make them complex.

**Comment by mrtztg** [comment]
Can you describe it more?
I want to develop it.
