### ISSUE TITLE
support Cassandra as data store

### ISSUE THREAD

**Issue by Somiacao** [gorse-io/gorse#356]
Apache Cassandra is a popular open source NoSQL distributed database.

## Design

Use Go CQL Driver:

https://github.com/MichaelS11/go-cql-driver

**Comment by BlakeB415** [comment]
This would be great as a cache data store as well.

**Comment by simanlx** [comment]
我也准备用 Cassandra

**Comment by zhenghaoz** [comment]
> 我也准备用 Cassandra

Cassandra的AP特性比较适合推荐系统，但是目前比较忙无法排期给它。如果有兴趣帮忙实现可以联系我哈

**Comment by zhenghaoz** [comment]
Cassandra won't be supported because it doesn't support global secondary index.
