### ISSUE TITLE
Memory build-up on Redis

### ISSUE THREAD

**Issue by guiscaranse** [gorse-io/gorse#391]
**Gorse version**
0.3.4

**Describe the bug**
I've been noticing a memory build-up (probably a leakage) on the Gorse Database used on Redis. Not sure why but the memory has been slowly building until it reaches 100%.

**To Reproduce**
Let gorse running for a few days and memory should hit 100%.

**Comment by zhangzhenghao** [comment]
Do you know which keys use up memory. 

You could try to list all keys an their data size.

**Comment by guiscaranse** [comment]
Sorry for the late response, it is being difficult to troubleshoot this issue but saw that you put a possible fix (#395) together. Have upgrade to 0.3.4 and will be watching for possible leakage

**Comment by zhenghaoz** [comment]
> Sorry for the late response, it is being difficult to troubleshoot this issue but saw that you put a possible fix (#395) together. Have upgrade to 0.3.4 and will be watching for possible leakage

I think the memory leakage fixed by #395 is insignificant. More debug info is required to fix memory leakage completely.

**Comment by guiscaranse** [comment]
Have new insights on the issue:
<img width="926" alt="Captura de Tela 2022-03-14 às 18 34 26" src="https://user-images.githubusercontent.com/4432205/158265158-361296f2-943a-4190-aff8-abb4add1bbbb.png">
Looks like `item_neighbors` is taking a significant amount of memory.

**Comment by zhenghaoz** [comment]
Now 0.4 has been released, which stores results on disk-based database.
