### ISSUE TITLE
Remove sensitive information from logs

### ISSUE THREAD

**Issue by guiscaranse** [gorse-io/gorse#458]
**Gorse version**
0.4.2

**Describe the bug**
Gorse outputs database information on logs by line
https://github.com/gorse-io/gorse/blob/master/server/server.go#L139

**Expected behavior**
Don't output sensitive information in logs.

**Comment by zhenghaoz** [comment]
There are several options:
1. Replace username and password with meaningless ******;
2. Replace username and password with same length ******;
3. Replace part of username and password with ******.

For security, 1 is the best. For debug, 3 is the best. Do you have any idea

**Comment by guiscaranse** [comment]
@zhenghaoz I think either 1 or 2 is fine, will leave up to you to decide but IMO 1 is best with fixed lenght (like always return 8 *)

**Comment by zhenghaoz** [comment]
OK. I think the length (option 2) is useful for debugging (check username and password). Pull requests are welcome. Otherwise, I will fix it this weekend.
