### ISSUE TITLE
使用gorse-in-one_darwin_amd64, 启动不久后, panic了

### ISSUE THREAD

**Issue by ppyupp** [gorse-io/gorse#483]
Please answer these questions before submitting your issue. Thanks!

**Gorse version**
0.4.4

**Describe the bug**
使用gorse-in-one_darwin_amd64, 启动不久后, panic了
配置文件用的是 config/config.toml.template
只是启动了程序, 还没有进行任何数据的操作
随后重启 ,加了一条item和user, 过1,2分钟, 还是同样的panic

{"level":"info","ts":1656045618.278102,"caller":"worker/worker.go:342","msg":"ranking recommendation","n_working_users":1,"n_jobs":1,"cache_size":100}
{"level":"info","ts":1656045618.285106,"caller":"worker/worker.go:369","msg":"start building ranking index"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1f1a88c]

goroutine 98 [running]:
github.com/zhenghaoz/gorse/worker.(*Worker).Recommend(0xc000192000, {0xc0001030e0, 0x1, 0x1})
	/home/runner/work/gorse/gorse/worker/worker.go:371 +0x76c
github.com/zhenghaoz/gorse/worker.(*Worker).Serve.func1()
	/home/runner/work/gorse/gorse/worker/worker.go:318 +0x37c
github.com/zhenghaoz/gorse/worker.(*Worker).Serve(0xc000192000)
	/home/runner/work/gorse/gorse/worker/worker.go:324 +0xced
main.glob..func1.1()
	/home/runner/work/gorse/gorse/cmd/gorse-in-one/main.go:70 +0xc5
created by main.glob..func1
	/home/runner/work/gorse/gorse/cmd/gorse-in-one/main.go:64 +0x47d

**Comment by zhenghaoz** [comment]
我也遇到了😂
