### ISSUE TITLE
Additional Database Prefixes postgresql:// and rediss://

### ISSUE THREAD

**Issue by bradrisse** [gorse-io/gorse#496]
**Is your feature request related to a problem? Please describe.**
I am attempting to use DigitalOcean's managed databases for gorse to use, but Digital ocean uses `postgresql://` and `rediss://` for their connection string prefixes

**Describe the solution you'd like**
Please add the `postgresql://` and `rediss://` to the allowed prefix lists

**Describe alternatives you've considered**
I was able to use Digital Ocean's Mongo database but without Redis I would loose speed enhancements

**Additional context**
https://github.com/gorse-io/gorse/blob/f4a66063dd350b50b82504f909e893dfc541488d/storage/scheme.go#L25

**Comment by zhenghaoz** [comment]
Is `rediss` means Redis with TLS?

**Comment by bradrisse** [comment]
yes
