### ISSUE TITLE
Add prefix for table names

### ISSUE THREAD

**Issue by almare** [gorse-io/gorse#497]
Currently it is not possible to change the table names of gorse. For example add a table name prefix to modify the Users table to devUsers. 

This would make it possible to integrate the databases (mysql,redis, ...) into other software easily and reduce the docker overhead just to the master and worker. At the moment I have already a table which is named Users and I am not responsible for this table. I have to add my developer prefix to my own tables to extend the functionality. 

The table prefix should offer the option to reuse the already existing mysql and redis instance if available.

Add a configurable prefix inside config.toml for example prefix + orginalTablename.

**Comment by zhenghaoz** [comment]
Good idea. Prefixes are common in many software.

**Comment by almare** [comment]
Perfect and soo fast thank you for your work!!
