### ISSUE TITLE
[solved] Extend the api to get last viewed items

### ISSUE THREAD

**Issue by almare** [gorse-io/gorse#498]
I know the recommender is responsible for making recommends, but I think it would be useful to get access to the last viewed items over the api. This should be easily made.

All the needed data is already collected for gorse. So it would be nice to get access to the last 10 viewed items, instead of collecting the same data again.

I know this is not the primary goal of you recommender, but I guess this is also a typical use case for others.

**Comment by zhenghaoz** [comment]
You could try this:

```bash
curl -X GET "http://127.0.0.1:8088/api/user/{user-id}/feedback" -H "accept: application/json"
```

**Comment by almare** [comment]
Thank you I will try it

**Comment by zhenghaoz** [comment]
We will try to add a `n` parameter to control the number of returned items.

**Comment by almare** [comment]
Works perfectly!!! Thank you very much.

**Comment by zhenghaoz** [comment]
This issue will be closed since the question has been solved. Welcome to open new issues or discussions if you have other questions.
