### ISSUE TITLE
Slow tasks

### ISSUE THREAD

**Issue by guiscaranse** [gorse-io/gorse#509]
Please answer these questions before submitting your issue. Thanks!

**Gorse version**
0.4.5

**Describe the bug**
My tasks have been taking several days to complete (sometimes never completing), I am wondering if this is normal or I am doing something wrong. 
<img width="1424" alt="Captura de Tela 2022-07-26 às 14 17 41" src="https://user-images.githubusercontent.com/4432205/181082412-959145e7-c4c5-4cbb-95ac-650fe2019bc1.png">

**Additional context**
- Items: 724173
- Number of User Labels: 2570647
- Number of Item Labels: 2571813
- Master RAM: 6gb
- Master CPU Cores: 2 CPU cores
- Number of tasks on master (config.yml): 8

**Comment by zhenghaoz** [comment]
There are two problems:
1. Gorse can't run multiple tasks concurrently. A slow task will block following tasks. This problem will be addressed in the next version.
2. It seems that you have too much labels. Are they really needed? And how many labels each user or item has? I think you should review your dataset.

**Comment by guiscaranse** [comment]
>It seems that you have too much labels. Are they really needed? And how many labels each user or item has? I think you should review your dataset.

@zhenghaoz an item has around 40 tags, is that a large amount? What would be a good amount of tags from a performance standpoint?

**Comment by zhenghaoz** [comment]
> > It seems that you have too much labels. Are they really needed? And how many labels each user or item has? I think you should review your dataset.
> 
> @zhenghaoz an item has around 40 tags, is that a large amount? What would be a good amount of tags from a performance standpoint?

Are these tags shared by multiple items?

**Comment by guiscaranse** [comment]
They are, I've started sampling the tags and reduced them by 95% and now the training is pretty fast (went from 5 days to 1 hour). Closing this issue :)
