### ISSUE TITLE
Can't access documentation

### ISSUE THREAD

**Issue by jayecc** [gorse-io/gorse#510]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/68594713/182011681-e357d1f7-4938-4bfe-aa23-0555a43bc92c.png">

**Comment by zhenghaoz** [comment]
Thanks. The custom domain issue has been fixed:

https://github.com/gorse-io/docs/commit/9708668a9fe2721452afbb83262d00ec07689b39
