### ISSUE TITLE
gorse-in-one  跑一段时间后 panic

### ISSUE THREAD

**Issue by jayecc** [gorse-io/gorse#511]
{"level":"info","ts":1659334556.2602627,"caller":"ranking/model.go:396","msg":"fit bpr","train_set_size":121468,"test_set_size":1138,"params":{"InitMean":0,"InitStdDev":0.001,"Lr":0.1,"NEpochs":100,"NFactors":32,"Reg":0.05},"config":{"Jobs":1,"Verbose":10,"Candidates":100,"TopK":10,"Task":{"Name":"Fit collaborative filtering model","Status":"Running","Done":0,"Total":100,"StartTime":"2022-08-01T06:15:56.260194922Z","FinishTime":"0001-01-01T00:00:00Z","Error":""}}}
panic: floats: slice lengths do not match

goroutine 84 [running]:
github.com/zhenghaoz/gorse/base/floats.Dot(...)
	/go/gorse/base/floats/floats.go:167
github.com/zhenghaoz/gorse/base/search.(*DenseVector).Distance(0x40d3d4, {0x1b398b0?, 0xc0292c8380?})
	/go/gorse/base/search/index.go:56 +0x2f4
github.com/zhenghaoz/gorse/base/search.(*HNSW).distance(0xc0058640c0, {0x1b398b0, 0xc0292c8380}, {0xc0076272d4, 0x1, 0xed0000c01de35500?})
	/go/gorse/base/search/hnsw.go:299 +0xe9
github.com/zhenghaoz/gorse/base/search.(*HNSW).efSearch(0xc0058640c0, {0x1b398b0, 0xc0292c8380}, 0xb?)
	/go/gorse/base/search/hnsw.go:441 +0x53
github.com/zhenghaoz/gorse/base/search.(*HNSW).MultiSearch(0xc0058640c0, {0x1b398b0, 0xc0292c8380}, {0xc0243de000, 0x2, 0x4?}, 0x69, 0x0)
	/go/gorse/base/search/hnsw.go:419 +0xc9
github.com/zhenghaoz/gorse/worker.(*Worker).collaborativeRecommendHNSW(0xc000146500, 0xc000000016?, {0xc0296996ec, 0x4}, {0xc0243de000, 0x2, 0x2}, 0xc007627b98, 0xc003e04260)
	/go/gorse/worker/worker.go:789 +0x1c5
github.com/zhenghaoz/gorse/worker.(*Worker).Recommend.func2(0xc01341b400?, 0x16)
	/go/gorse/worker/worker.go:510 +0xafc
github.com/zhenghaoz/gorse/base/parallel.Parallel(0xdec, 0xc019c343b0?, 0xc01c23d3b0)
	/go/gorse/base/parallel/parallel.go:31 +0xff
github.com/zhenghaoz/gorse/worker.(*Worker).Recommend(0xc000146500, {0xc02b41e000, 0xdec, 0xf99})
	/go/gorse/worker/worker.go:463 +0xfbb
github.com/zhenghaoz/gorse/worker.(*Worker).Serve.func1()
	/go/gorse/worker/worker.go:329 +0x37c
github.com/zhenghaoz/gorse/worker.(*Worker).Serve(0xc000146500)
	/go/gorse/worker/worker.go:336 +0xd7f
main.glob..func1.1()
	/go/gorse/cmd/gorse-in-one/main.go:114 +0x96
created by main.glob..func1
	/go/gorse/cmd/gorse-in-one/main.go:109 +0xabb

**Comment by zhenghaoz** [comment]
看来all in one模式下要强制模型大小不变了：https://github.com/gorse-io/gorse/pull/502

**Comment by zhenghaoz** [comment]
已经在#502 解决了，关闭issue
