### ISSUE TITLE
Support `postgresql` prefix

### ISSUE THREAD

**Issue by Huskydog9988** [gorse-io/gorse#515]
**Is your feature request related to a problem? Please describe.**
Currently, only the `postgres` prefix is allowed for postgres, while its fairly normal to use the `postgresql` prefix. Leading to a weird moment where you have to question if postgres is supported.

**Describe the solution you'd like**
Check for both `postgres` and `postgresql` as prefixes for postgres.

**Describe alternatives you've considered**
You could tell users to change the prefix.

**Comment by zhenghaoz** [comment]
Duplicate to #499
