### ISSUE TITLE
quick-start doc problem

### ISSUE THREAD

**Issue by dchack** [gorse-io/gorse#553]
**Gorse version**
 latest version

**Describe the bug**
wget https://raw.githubusercontent.com/zhenghaoz/gorse/master/docker/docker-compose.yml
wget https://raw.githubusercontent.com/zhenghaoz/gorse/master/docker/config.toml
**Url is 404**

**Comment by zhenghaoz** [comment]
Sorry for the outdated documents. You may try these two files:
- https://github.com/gorse-io/gorse/blob/master/docker-compose.yml
- https://github.com/gorse-io/gorse/blob/master/config/config.toml.template

**Comment by dchack** [comment]
thanks, it works.
