### ISSUE TITLE
关于master一些tasks暂停以及未更新问题

### ISSUE THREAD

**Issue by AcSunday** [gorse-io/gorse#556]
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/40159235/190088009-3d9eedec-46c2-4755-ae3b-d57f47827517.png">
协同过滤和一些其它任务有几天没更新了，日志上也没看出有报错。

**Comment by AcSunday** [comment]
worker的任务一直在运行，其它红色方框的任务等待了两天没有更新状态。

**Comment by zhenghaoz** [comment]
更新到0.4.7试试，应该是#554的问题，已经被修复了

**Comment by AcSunday** [comment]
好的谢谢，我尝试升级一下版本
