### ISSUE TITLE
support more APIs in Go client

### ISSUE THREAD

**Issue by zhenghaoz** [gorse-io/gorse#563]
**Is your feature request related to a problem? Please describe.**
The current go client supports only limited APIs and their parameters.

**Describe the solution you'd like**
Support more APIs and their parameters in the Go client.

**Describe alternatives you've considered**
Send HTTP requests manually.

**Additional context**
- [RESTful APIs | Gorse Docs](https://docs.gorse.io/quick-start/restful-apis.html#authorization)
- [client package - github.com/zhenghaoz/gorse/client - Go Packages](https://pkg.go.dev/github.com/zhenghaoz/gorse@v0.4.7/client)

**Comment by angelorc** [comment]
I can jump on it. I'm using the go client

**Comment by zhenghaoz** [comment]
> I can jump on it. I'm using the go client

Appreciate it.

**Comment by CyJaySong** [comment]
可以关闭了😁

**Comment by zhenghaoz** [comment]
> 可以关闭了😁

是的哈哈
