### ISSUE TITLE
Expose Tasks to REST API

### ISSUE THREAD

**Issue by josepowera** [gorse-io/gorse#572]
**Is your feature request related to a problem? Please describe.**
We have to run multiple gorse servers to have multi-tenancy (that we believe is not supported ATM). They run as pods in single kubernetes cluster.

**Describe the solution you'd like**
In order not to overload our server we would like to "manually coordinate - dispatch" tasks for multiple tenants (multiple Gorse servers) that we find in Tasks dashboard.  This also helps in case that we would like to delay Tasks to "night only" hours -to keep daily CPU for real endusers.

Another alternative could be maybe also, to use CRON expressions instead of "every 24 house". This way we could at least spread CPU intensitive tasks.

This coule be done as REST/GRPC endpoint similar to existing REST endpoint. 
-REST POST endpoint for starting specific task
-REST GET endpoint to receive current progress for specific task (we can use http://..../api/dashboard/tasks)

**Comment by zhenghaoz** [comment]
Good idea. In current design, we could expose an API to start all tasks manually. But it is hard to control individual tasks.

**Comment by zhenghaoz** [comment]
An admin API has been provided in #575, and the detailed documentation will come later.
