### ISSUE TITLE
cdn好像不太稳定

### ISSUE THREAD

**Issue by warrana2321** [gorse-io/gorse#574]
https://cdn.gorse.io/example/github.sql
经常访问不了，但有时候又可以

会造成docker安装的时候错误

`[root@loaclhost ~]# docker run -p 8088:8088 zhenghaoz/gorse-in-one --playground
Welcome to Gorse v0.4.8 Playground
{"level":"fatal","ts":1666740804.338797,"caller":"gorse-in-one/main.go:89","msg":"failed to initialize database","error":"Get \"https://cdn.gorse.io/example/github.sql\": dial tcp 185.183.84.75:443: i/o timeout","errorVerbose":"Get \"https://cdn.gorse.io/example/github.sql\": dial tcp 185.183.84.75:443: i/o timeout\nmain.initializeDatabase:177: ","stacktrace":"main.glob..func1\n\t/go/gorse/cmd/gorse-in-one/main.go:89\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t/go/gorse/cmd/gorse-in-one/main.go:144\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
`

**Comment by zhenghaoz** [comment]
因为它被GFW墙了，我后面换一下服务器

**Comment by josepowera** [comment]
Why not add this .sql inside docker container used forzhenghaoz/gorse-in-one.. It's true, that it takes 31MB but compressed using zip or similar it would take only a few MB, and most users prefer software not to be dependent on external source - after docker container is already built.

**Comment by zhenghaoz** [comment]
> Why not add this .sql inside docker container used forzhenghaoz/gorse-in-one.. It's true, that it takes 31MB but compressed using zip or similar it would take only a few MB, and most users prefer software not to be dependent on external source - after docker container is already built.

The SQL script is dynamic content. It is inconvenient to update it if published with `gorse-in-one`.

**Comment by zhenghaoz** [comment]
已经迁移至大陆可以访问的服务器上：https://cdn.gorse.io/
