### ISSUE TITLE
Excluding items with 'read' feedback from popular/latest recommendations

### ISSUE THREAD

**Issue by paulroeder** [gorse-io/gorse#592]
**Is your feature request related to a problem? Please describe.**
I'm building a feed of recommendations (e.g. TikTok) where each item is recommended once only until 'read' feedback. Currently, the popular or latest recommenders don't exclude items with 'read' feedback. Also, when increasing the 'explore_recommend' values, the User-based Similarity Recommender includes the same latest or popular items every time, showing duplicates to user. 

**Describe the solution you'd like**
Config to exclude latest or popular items with 'read' feedback in recommendations.

**Describe alternatives you've considered**
Tried scrolling through result lists with the cursor option but not ideal because fresh recommendations should be based on user feedbacks as the user consumes the content.

**Comment by hitech95** [comment]
Would be cool to be able to do this by passing the `user_id` to the endpoint.

For what i reremember `popular` and `latest` indexes are not connected to a  specific user.

**Comment by zhenghaoz** [comment]
A query parameter has been added to removed read items for a user. You could preview it in the nightly version or v0.4.10.
