### ISSUE TITLE
Gorse worker refreshCache panic.

### ISSUE THREAD

**Issue by binary4cat** [gorse-io/gorse#608]
Please answer these questions before submitting your issue. Thanks!

**Gorse version**
```shell
Version:         v0.4.10-4-g762f21f
API version:     v0.2.7
Go version:      go1.19.4
Git commit:      762f21f3154f35877fe376ba435c11e7eaaf5edc
Built:           Fri Jan  6 09:00:06 UTC 2023
OS/Arch:         linux/amd64
```

**Describe the bug**
In the worker, the `LastUpdateUserRecommendTime` (worker/worker.go:1120) data in the cache is read in the `refreshCache` (worker/worker.go:1117) function, but for unknown reasons, it is not found, resulting in an error, but the error handling only determines the error except for the not found case, resulting in the `timeLimit` (worker/worker.go:1118) not being initialized to always be nil, which leads to a panic in the `RemSortedByScore` (worker/worker.go:1150) delete method calling `timeLimit`.

Since I don't understand the process here, I'm not sure if the not found error should be returned, so I need your help!

This is what I found after using mongodb, and it was not found when using redis and mysql.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by zhenghaoz** [comment]
Thanks for your feedback. What kinds of Mongo deployment do you use? Single node or cluster.

**Comment by binary4cat** [comment]
> Thanks for your feedback. What kinds of Mongo deployment do you use? Single node or cluster.
Thanks for your work, I use a cluster with three nodes.

**Comment by zhenghaoz** [comment]
> > Thanks for your feedback. What kinds of Mongo deployment do you use? Single node or cluster.
> 
> Thanks for your work, I use a cluster with three nodes.

It is caused by inconsistent read between nods.
