### ISSUE TITLE
goat: dedicated go.mod

### ISSUE THREAD

**Issue by asdine** [gorse-io/gorse#720]
**Is your feature request related to a problem? Please describe.**
Goat is an amazing tool but it is difficult to use it in another project without having to depend on Gorse and all its dependencies.

**Describe the solution you'd like**
It would great if Goat had its own go module, either in the gorse repo or as a standalone repository.

**Describe alternatives you've considered**
I considered copying the goat source code and updating it manually every time there's an update but that's not sustainable.

**Comment by asdine** [comment]
Of course, thanks!

**Comment by asdine** [comment]
I have extracted the code to the standalone repo and did the following:
- kept the orignal commit history
- added the original readme
- added a go.mod / go.sum files

I will probably create a v0.1 release so that anyone can select a fixed version.

**Comment by zhenghaoz** [comment]
Than you so much
