### ISSUE TITLE
Import from csv improvement

### ISSUE THREAD

**Issue by huaesthetica63** [gorse-io/gorse#746]
Hello! I had some problems with csv-import at Gorse-dashboard. If some of rows are incorrect (my rows had slash-symbol in labels), then import interrupts with error. I think that it would be better if incorrect rows will be just skipped without interrupting import

**Comment by zhenghaoz** [comment]
Thanks for your suggestions. Skip interruption could be an option in the import UI.

**Comment by huaesthetica63** [comment]
Hello again! I can't see any button or checkbox for skipping interruptions. I think that code needs to be changed for this feature.

**Comment by huaesthetica63** [comment]
Can I fork your project and add this feature? I will be happy if you allow me this.

**Comment by zhenghaoz** [comment]
Glad to know that you are interested in it. There are two steps to support interruption skipping:

1. Add a new option in import UIs on the dashboard:
https://github.com/gorse-io/dashboard/blob/master/src/views/ImportFeedback.vue
https://github.com/gorse-io/dashboard/blob/master/src/views/ImportItems.vue
https://github.com/gorse-io/dashboard/blob/master/src/views/ImportUsers.vue
3. Pass this option to import APIs:
https://github.com/gorse-io/gorse/blob/master/master/rest.go

**Comment by zhenghaoz** [comment]
This issue could be closed since CSV has been deprecated in #885
