### ISSUE TITLE
gores的整体架构有具体的介绍吗

### ISSUE THREAD

**Issue by wanghai345** [gorse-io/gorse#748]
gores的整体架构有具体的介绍吗，比如架构图或者文档什么的。

**Comment by zhenghaoz** [comment]
文档有介绍：https://gorse.io/zh/docs/master/concepts/how-it-works.html

**Comment by wanghai345** [comment]
嗯嗯，谢谢啦，打算用到生产环境中，可以吗。

**Comment by zhenghaoz** [comment]
每个人的生产环境软硬件条件和推荐需求都不太一样，是否使用需要自行测试。

**Comment by wanghai345** [comment]
目前有用在生产环境的case吗。如果有，就不怕了。

**Comment by zhenghaoz** [comment]
即使再成熟，Bug也不可避免，不管怎么样都需要在使用Gorse的同时具备兜底方案。

**Comment by wanghai345** [comment]
好的。谢谢啦。
