### ISSUE TITLE
0.5版本 work 启动加线程参数会down机

### ISSUE THREAD

**Issue by Anymous526** [gorse-io/gorse#806]
Please answer these questions before submitting your issue. Thanks!

**Gorse version**
Print build info by the `--version` option.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**
![1709022396860](https://github.com/gorse-io/gorse/assets/7920015/ad5b92b2-ee74-4d24-96fb-8458562f3483)

**Comment by zhenghaoz** [comment]
已经在 #873 修复
