### ISSUE TITLE
categories []string 不生效啊  项目不在维护了么?

### ISSUE THREAD

**Issue by simanlx** [gorse-io/gorse#837]
`func (c *GorseClient) GetItemRecommend(ctx context.Context, userId string, categories []string, writeBackType, writeBackDelay string, n, offset int) ([]string, error) {
	var queryCategories string
	if len(categories) > 0 {
		queryCategories = "&category=" + strings.Join(categories, "&category=")
	}
	return request[[]string, any](ctx, c, "GET", c.entryPoint+fmt.Sprintf("/api/recommend/%s?write-back-type=%s&write-back-delay=%s&n=%d&offset=%d%s", userId, writeBackType, writeBackDelay, n, offset, queryCategories), nil)
}`

categories []string  获取的并非分类下的Item

**Comment by Tobi-Tr** [comment]
Same here
