### ISSUE TITLE
启动项目时 相邻用户和物品都报错

### ISSUE THREAD

**Issue by Winged-angel** [gorse-io/gorse#841]
![image](https://github.com/gorse-io/gorse/assets/42825583/2cb4b8ce-53a8-4efc-8429-3fc6d8742dca)

我看代码内部从redis 取出来数据类型是 map[interface {}]interface {}   但是这个parseSearchDocumentsResult 函数内部判断的是 []any  类型错误  希望作者可以帮忙解惑

**Comment by zhenghaoz** [comment]
大概率版本问题，你试着让RediSearch版本号和测试中的版本号对齐

**Comment by Winged-angel** [comment]
非常感谢您抽空帮忙查看问题 确实是redisearch 版本的问题  修正后已经不报错了
