### ISSUE TITLE
Live demo website dosent work

### ISSUE THREAD

**Issue by gnovaro** [gorse-io/gorse#852]
Please answer these questions before submitting your issue. Thanks!

![image](https://github.com/user-attachments/assets/957ccab1-0f16-4dd5-9353-4f4ceb00ba54)

**Gorse version**
-

**Describe the bug**
This link dosent work
https://gitrec.gorse.io/

**To Reproduce**
Just navigate the website

**Expected behavior**
Loads the website correctly

**Additional context**
SSL error

**Comment by zhenghaoz** [comment]
Thank you for your feedback. The demo has been recovered now: [![Website](https://img.shields.io/website?url=https%3A%2F%2Fgitrec.gorse.io)](https://gitrec.gorse.io)
