### ISSUE TITLE
Live Demo showing cloudflare '526:Invalid SSL certificate' - unable to access Live Demo

### ISSUE THREAD

**Issue by smck83** [gorse-io/gorse#859]
Please answer these questions before submitting your issue. Thanks!

**Gorse version**
N/A - latest version running on Live Demo?

**Describe the bug**
I am unable to access the Live demo environment hosted here https://gitrec.gorse.io/ due to a certificate issue served by Cloudflare -  '526:Invalid SSL certificate' 

**To Reproduce**
Visit https://gitrec.gorse.io/ and you will be served with a Cloudflare page:
````
Invalid SSL certificate Error code 526
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_526&utm_campaign=gitrec.gorse.io) for more information.
2024-09-22 22:54:34 UTC
````

**Expected behavior**
The live demo page should load and show me how Gorse looks/feels etc.

**Additional context**
Cloudflare Ray ID: 8c75e0a8cc56d5de

**Comment by zhenghaoz** [comment]
Thank you for your feedback. The demo has been recovered now: [![Website](https://img.shields.io/website?url=https%3A%2F%2Fgitrec.gorse.io)](https://gitrec.gorse.io)

**Comment by nktnet1** [comment]
Demo site is down once again:

![demo-site-down](https://github.com/user-attachments/assets/13f51899-55ab-4bfb-b8fd-f50bdc8eb54a)
