### ISSUE TITLE
Unable to Change Username and Password in Gorse

### ISSUE THREAD

**Issue by Ramgahalout23** [gorse-io/gorse#876]
I am unable to change the username and password for the Gorse  when running the application using Docker.

can u suggest some steps for change this one

**Comment by zhenghaoz** [comment]
How you change username and password?

**Comment by Ramgahalout23** [comment]
i,m changing username and password using docker commands

**Comment by zhenghaoz** [comment]
You can change username and password in config file or via environment variables:
https://gorse.io/docs/master/config.html
