### ISSUE TITLE
redis big key problem

### ISSUE THREAD

**Issue by unknownYuan** [gorse-io/gorse#890]
在生产环境，我们部署gorse之后，发现gorse使用了错误的数据结构，
<img width="835" alt="image" src="https://github.com/user-attachments/assets/e2ede55e-1ae6-4536-a216-7318c2cd14be">
如图所示，使用zadd ，当参数变多时，会阻塞其他命令的正常执行。建议在协同过滤推荐中用其他方式替代zadd，如果数据越多，redis的性能和响应时间越低，命令执行的等待时间越高。

**Comment by zhenghaoz** [comment]
0.5版本已经放弃了ZADD，但是依赖RediSearch
